### PR TITLE
Copy Cabal file

### PR DESCRIPTION
**Pull request by leungbk**

### CODE REVIEW

**Comment by leungbk** [comment]
Friendly ping @DavHau @m1-s.

**Comment by m1-s** [comment]
Looks good to me. I assume DavHau knows the motivation for this so I will let him press the merge button.

**Comment by leungbk** [comment]
The motivation is https://github.com/nix-community/dream2nix/pull/228#issuecomment-1211972400, specifically

> Also I think, eventually we should only use one of the all-cabal-... repos. I think we should update all-cabal-json to also contain the cabal files. Then we can get rid of all-cabal-hashes.

**Comment by DavHau** [comment]
Thanks. Sorry I missed that one for a while. Feel free to ping earlier next time.

**Pull request merged**
